# Pump automation
#
# Truth table.
#
# Aut = Turn off the pump when there is not water in the well,
# turn it back on when it comes back automation enabled/disabled.
# Wel = Water present in the well
# Des = Pump desired state
# Pum = Pump actual state
#
# Aut Wel Des Pum
# 0   0   0   0
# 0   0   1   1
# 0   1   0   0
# 0   1   1   1
# 1   0   0   0
# 1   0   1   0
# 1   1   0   0
# 1   1   1   1
#
# Pum = (!Aut * Des) + (Aut * Wel * Des)
- id: pump
  alias: pump
  initial_state: on
  trigger:
    # Aut
    - platform: state
      entity_id: input_boolean.automation_pump_off_when_no_water
    # Wel
    - platform: state
      entity_id: binary_sensor.well
    # Des
    - platform: state
      entity_id: input_boolean.pump_desired_state
  action:
    - service_template:
        "switch.\
        {%
          if
            (
              not is_state('input_boolean.automation_pump_off_when_no_water', 'on')
              and
              is_state('input_boolean.pump_desired_state', 'on')
            )
            or
            (
              is_state('input_boolean.automation_pump_off_when_no_water', 'on')
              and
              is_state('binary_sensor.well', 'on')
              and
              is_state('input_boolean.pump_desired_state', 'on')
            )
        %}\
          turn_on\
        {% else %}\
          turn_off\
        {% endif %}"
      entity_id: switch.pump


# Power state sync (https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant#tip-sync-power-state)
- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "sonoffs/cmnd/state"
        payload: ""
