# Dacha
title: Дача
views:
  # General
  - title: Общее
    cards:
      # Pump
      - title: Насос
        type: entities
        show_header_toggle: false
        entities:
          # TODO Only show pump's actual state, don't allow switching it directly.
          # Or maybe allow swithing it directly, when automatizations are off?
          # Consider using group.set_visibility
          - input_boolean.pump_desired_state
          - type: divider
          - binary_sensor.pump_state
          - binary_sensor.well
          - binary_sensor.tank
          - type: divider
          - switch.automation_pump_off_when_no_water
      - title: Debug
        type: entities
        show_header_toggle: false
        entities:
          - input_boolean.well_stub
          - input_boolean.pump_stub
          - input_boolean.tank_stub
