# Dacha
title: Дача
views:
  # General
  - title: Общее
    cards:
      # Pump
      - title: Насос
        type: entities
        show_header_toggle: false
        entities:
          - input_boolean.pump_desired_state
          - type: divider
          - binary_sensor.pump_state
          - timer.pump_break
          - binary_sensor.well
          - binary_sensor.tank
          - type: divider
          - input_boolean.automation_pump_off_when_well_empty
          - input_boolean.automation_pump_off_when_tank_full
          - input_number.pump_break_duration
      - type: picture-entity
        entity: camera.usb_camera_1
        show_name: no
        show_state: no
      - type: entities
        title: Мобильная розетка
        show_header_toggle: false
        entities:
          - switch.sonoff_plug
          - sensor.sonoff_plug_status
