# Dacha
title: Дача
views:
  # General
  - title: Общее
    cards:
      # Pump
      - title: Насос
        type: entities
        show_header_toggle: false
        entities:
          # TODO Only show pump's actual state, don't allow switching it directly.
          # Or maybe allow swithing it directly, when automatizations are off?
          # Consider using group.set_visibility
          - input_boolean.pump_desired_state
          - type: divider
          - binary_sensor.pump_state
          - binary_sensor.well
          - binary_sensor.tank
          - type: divider
          - input_boolean.automation_pump_off_when_no_water
      - type: picture-entity
        entity: camera.usb_camera_1
        show_name: no
        show_state: no
      - type: entities
        title: Мобильная розетка
        show_header_toggle: false
        entities:
          - switch.sonoff_plug
          - sensor.sonoff_plug_status
