# Dacha
title: Дача
views:
  # General
  - title: Общее
    cards:
    - type: entities
      # Pump
      title: Насос
      show_header_toggle: false
      entities:
        - entity: sensor.well
        - entity: sensor.tank
        - entity: automation.pump_prevent_idling
          name: "Не допускать работы вхолостую"
